# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FilesCli < Formula
  desc "Official Pinata IPFS CLI written in Go"
  homepage "https://github.com/PinataCloud/ipfs-cli"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PinataCloud/ipfs-cli/releases/download/v0.0.4/ipfs-cli_Darwin_x86_64.tar.gz"
      sha256 "d0ee95b0d4e68485459bef41495a141d761895c376b0f3e9b1e61d5824ba4668"

      def install
        bin.install "pinata"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PinataCloud/ipfs-cli/releases/download/v0.0.4/ipfs-cli_Darwin_arm64.tar.gz"
      sha256 "8bb8883c8172d2323ed10c05cc4ae6aec669b8050e1f02792c340a4e221d7de0"

      def install
        bin.install "pinata"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/PinataCloud/ipfs-cli/releases/download/v0.0.4/ipfs-cli_Linux_x86_64.tar.gz"
        sha256 "284be3c323410a38c4807ebcefb2df4ee6db453d5dbf96ede2f4d2db73e42d05"

        def install
          bin.install "pinata"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/PinataCloud/ipfs-cli/releases/download/v0.0.4/ipfs-cli_Linux_arm64.tar.gz"
        sha256 "6443b84ed08009430e96b5f3d8f12aabd3d0b27c30f556d617b74f2c0d48bb89"

        def install
          bin.install "pinata"
        end
      end
    end
  end
end
