# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class IpfsCli < Formula
  desc "Official Pinata IPFS CLI written in Go"
  homepage "https://github.com/PinataCloud/ipfs-cli"
  version "0.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PinataCloud/ipfs-cli/releases/download/v0.0.6/ipfs-cli_Darwin_x86_64.tar.gz"
      sha256 "008d90b27f2e9e785699e0692632ef4b69f985d42572b9c2a05628215436f358"

      def install
        bin.install "pinata"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PinataCloud/ipfs-cli/releases/download/v0.0.6/ipfs-cli_Darwin_arm64.tar.gz"
      sha256 "2941cde05b4063b9e673243f2a80282f93b591fa926a4417fd5da516bec877da"

      def install
        bin.install "pinata"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/PinataCloud/ipfs-cli/releases/download/v0.0.6/ipfs-cli_Linux_x86_64.tar.gz"
        sha256 "1c621a758f54f40481738d84887f59af734c4826030dfd8c22cf0866716532c2"

        def install
          bin.install "pinata"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/PinataCloud/ipfs-cli/releases/download/v0.0.6/ipfs-cli_Linux_arm64.tar.gz"
        sha256 "b4c4e57a548a40fdea5e26aae21fe60eb183abbc12c480a73f1c5f1338f62995"

        def install
          bin.install "pinata"
        end
      end
    end
  end
end
